apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-lab
spec:
  containers:
  - image: nginx:1.27
    name: nginx-lab
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
